moods = ["Happy", "Funny", "Sad", "Tender", "Exciting", "Angry", "Scary"]

genres = ["Pop", "Hip Hop", "Rock",
            "R&B", "Soul", "Reggae",
            "Country", "Funk", "Folk",
            "Middle Eastern", "Jazz", "Disco",
            "Classical", "Electronic", "Latin",
            "Blues", "Chilren's", "New-age",
            "Vocal", "Music of Africa", "Christian",
            "Music of Asia", "Ska", "Traditional",
            "Independent"]

genre_prompts = ["* pop music artist performing",    # Pop
                 "* hip hop artists dancing on the street, detailed faces", # Hip Hop, 
                 "* rock and roll performer with a guitar on a stage", # Rock,
                 "*, classy late night performer", # R&B, 
                 "spiritual and moody musician who is well dressed and *", # Soul, 
                 "reggae musician who looks very *", # Reggae,
                 "* cowboy with a very large hat and a cold beer", # Country, 
                 "funky man walking down the street in a * way", # Funk, 
                 "* woman singing around a campfire", # Folk,
                 "* middle eastern musician", # Middle Eastern, 
                 "late night jazz cafe, with a very * ambiance", # Jazz, 
                 "extremely * disco dancer", # Disco,
                 "pretentious person *ly playing the piano", # Classical, 
                 "colourful techno dancers *ly turning up the beat", # Electronic, 
                 "latin dancer who is very *", # Latin,
                 "old * man singing the blues in a smokey bar", # Blues, 
                 "* children's music", # Chilrens, 
                 "artistic person meditating, listening to * music", # New-age,
                 "* vocal music", # Vocal, 
                 "* music of africa", # Music of Africa, 
                 "* christian music", # Christian,
                 "* music of asia", # Music of Asia, 
                 "* ska music", # Ska, 
                 "* traditional music", # Traditional,
                 "* independent music"] # Independent